# Generated by Django 5.0.7 on 2024-08-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_order_address_order_created_order_items_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='ward',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
